### ISSUE TITLE
Apply the new pattern to create MasterPage

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Skyper#18]
A new pattern to create MasterPage was discussed in https://github.com/Starcounter/Guidelines/issues/23 and implemented for reference in https://github.com/StarcounterApps/Website/pull/106.

Please apply the same pattern in Skyper app, namely:

- replace `Handle.GET("/skyper/standalone"` handler with a `GetSessionFromMaster` method
- remove the `GetMaster` method

**Comment by warpech** [comment]
Suggested reviewer: @warpech

**Comment by Mackiovello** [comment]
Fixed with 	52a43c6, closing

@bouguila, please close issues when you've finished a task
