### ISSUE TITLE
Wrong slot name

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Skyper#24]
The slot attribute and the slot name in https://github.com/StarcounterApps/Skyper/blob/821132343f910a1b15b36ac64f7d172d5401805c/src/Skyper/wwwroot/Skyper/viewmodels/AppIconPage.html do not match.

cc @Mackiovello, @PatrykSzwer 

I assume that https://github.com/Starcounter/starcounter-debug-aid/pull/50 would detect that.

cc @tomalec

**Comment by Mihaiii** [comment]
Ugh, related to the CCs, It was ok when @Mackiovello reviewed it. I broke it later. 
Thank you, I will fix it soon.

**Comment by Mihaiii** [comment]
Closing as done.
