### ISSUE TITLE
Apply BEM to Skyper's private CSS

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Skyper#7]
This app contains globally applied CSS rules in stylesheets: 
- https://github.com/StarcounterSamples/Skyper/blob/a756ba9cb18247deab2dc1bf47f7ddaff685bf05/src/Skyper/wwwroot/css/skyper.css
- https://github.com/StarcounterSamples/Skyper/blob/a756ba9cb18247deab2dc1bf47f7ddaff685bf05/src/Skyper/wwwroot/css/standalone.css

All private CSS should be converted to BEM-style CSS classes defined in a stylesheet, according to the intent started in the issue https://github.com/Starcounter/Starcounter/issues/3450 and explained in the article http://starcounter.io/guides/web/avoiding-css-conflicts/

**Comment by mmnosek** [comment]
+1

**Comment by diliger** [comment]
PR #12

**Comment by diliger** [comment]
Done. Merged. Close.
